@startuml

class OceanParameters{
    -Vector oceanSize
    -Flow flow
    -OceanType oceanType
    -Integer passiveFishCount
    -Integer aggressiveFishCount
    -FishParameters passiveFishParameters
    -FishParameters aggressiveFishParameters
}
OceanParameters-->FishParameters
OceanParameters-->Flow
OceanParameters-->OceanType

class FishParameters{
    -Integer speed
    -Integer reproductionPeriodTicks
    -Integer lifeTimeTicks
    -Integer starvationTimeTicks
    -Integer smellSenseDistance
}

class Flow{
    Vector direction
    Integer strength
}

enum OceanType{
    BORDERED,
    BORDERLESS
}

interface OceanSimulation{
    void start()
}

OceanSimulation <|-- DefaultOceanSimulation

class DefaultOceanSimulation{
    -oceanCreator: OceanCreator
    -oceanRunner: OceanRunner
    -oceanRenderer: OceanRenderer
    -oceanMetricPrinter: OceanMetricPrinter
    DefaultOceanSimulation(OceanCreator,
    OceanRunner,OceanRenderer,OceanMetricPrinter)
    -void createOcean()
    +void start()

}

interface Runnable{
    void start()
}

Runnable <|-- OceanRunner
interface OceanRunner{
    void start()

}

OceanRunner <|-- DefaultOceanRunner
class DefaultOceanRunner{
    - queue BlockingQueue<OceanDto>
    - void addOceanSnapshot(OceanDto)
    - void updateOcean()
    + void start()
}
DefaultOceanRunner --> Ocean
DefaultOceanRunner -> BlockingQueue
DefaultOceanRunner --> OceanDtoCreator

interface OceanDtoCreator{
    OceanDto createDto(Ocean)
}

Runnable <|-- OceanRenderer
interface OceanRenderer{
    void start()

}

OceanRenderer <|-- DefaultOceanRenderer
class DefaultOceanRenderer{
    - queue BlockingQueue<OceanDto>
    - void renderOcean()
    - OceanDto pollOceanDto()
    + void start()

}
DefaultOceanRenderer --> BlockingQueue


interface Ocean{
    +void update()
    +List<Fish> getFishes()
}

interface OceanSpace{
    +List<Cell> getCellsInRange(Vector)
    +Vector modifyVelocity(Vector velocity)
    +void addFish(Fish)
}

OceanSpace <|-- DefaultOcean
Ocean <|-- DefaultOcean
class DefaultOcean{
    - fishes : List<Fish>
    - grid : CellGrid
    - cellsBehavior : CellsBehavior
    - flow : Flow

    +List<Cell> getCellsInRange(Vector)
    +Vector modifyVelocity(Vector velocity)
    +void addFish(Fish)
}
DefaultOcean --> CellsBehavior
DefaultOcean --> CellGrid
DefaultOcean --> Fish

interface CellGrid{
    + getCell(Vector)
}

CellGrid <|-- DefaultCellGrid
class DefaultCellGrid{
    -cells : Cell[][]
    + getCell(Vector)
}
DefaultCellGrid ---> Cell

class Vector{
    - x: Integer
    - y: Integer
}

interface Cell{
    + void add(Fish)
    + void remove(Fish)
    + List<Fish> getFishes()
}

Cell <|- DefaultCell
class DefaultCell{
    - position: Vector
    - fishes : Set<Fish>
    + void add(Fish)
    + void remove(Fish)
    + List<Fish> getFishes()
}

interface CellsBehavior{
    + getCellsInRadius(CellGrid, Vector, Integer distance)
    + resolveBorderCells(Ocean)
}

CellsBehavior<|--BorderlessCellBehavior
CellsBehavior<|--BorderedCellBehavior

interface Fish{
    + FishType getType()
    + Vector getPosition()
    + void action()
}

Fish<|--OceanFish
class OceanFish{
    - ocean: OceanSpace
    - state: FishState
    - fishType: FishType
    - strategy: MovingAnimalStrategy
    - reproductionBehavior : ReproductionBehavior
    + void changeState(FishState)
    + void action()
}
OceanFish-->OceanSpace
OceanFish->ReproductionBehavior
OceanFish-->TargetCalculationFishStrategy
OceanFish-->OceanFishState

interface ReproductionBehavior{
    + void birth(Ocean, Vector birthVec)
}

ReproductionBehavior<|--AggressiveReproductionFishBehavior
ReproductionBehavior<|--PassiveReproductionFishBehavior

interface TargetCalculationFishStrategy{
    + Vector calculateTarget(Ocean)
}

TargetCalculationFishStrategy<|--AggressiveTargetCalculationStrategy
TargetCalculationFishStrategy<|--PassiveTargetCalculationStrategy

interface OceanFishState{
    + action()
}

OceanFishState<|--BirthOceanFishState
class BirthOceanFishState{
    - fish : OceanFish
    - ticksToBecomeAdult : Integer
    + action()
}

OceanFishState<|--MovingOceanFishState
class MovingOceanFishState{
    - fish : OceanFish
    + action()
}

OceanFishState<|--EatingOceanFishState
class EatingOceanFishState{
    - fish : OceanFish
    + action()
}

interface OceanParametersReader{
    OceanParameters read(InputStream)
}

OceanParametersReader <|- OceanParametersReaderDecorator
abstract class OceanParametersReaderDecorator{
    -reader : OceanParametersReader
    +OceanParametersReaderDecorator(OceanParametersReader reader)
    +OceanParameters read(InputStream)
}

OceanParametersReaderDecorator <|- FileChangeBufferDecorator
class FileChangeBufferDecorator{
    -lastModifiedTimeStamp : Integer
    -lastModifiedOceanParameters : OceanParameters
    -checkFileLastModified()
    OceanParameters read(InputStream)
}
FileChangeBufferDecorator -> OceanParametersReader

OceanParametersReader <|-- DomOceanParametersReader
OceanParametersReader <|-- SaxOceanParametersReader
OceanParametersReader <|-- JaxbOceanParametersReader

interface OceanCreator{
    Ocean createOcean()
}

OceanCreator<|--XmlFileOceanCreator
class XmlFileOceanCreator{
    -paramsReader: OceanParametersReader
    Ocean createOcean()
}
XmlFileOceanCreator --> OceanParametersReader

DefaultOceanSimulation --> OceanRunner
DefaultOceanSimulation --> OceanRenderer
DefaultOceanSimulation --> OceanMetricPrinter

interface OceanCreatorFactory{
    OceanCreator createOceanCreator()
}

interface OceanMetricPrinter{

}

OceanMetricPrinter <|-- DefaultOceanMetricPrinter
class DefaultOceanMetricPrinter{

}

OceanCreatorFactory <|-- XmlWithFileChangeBufferOceanCreatorFactory

class XmlWithFileChangeBufferOceanCreatorFactory{
    -propertiesReader PropertiesReader
    XmlWithFileChangeBufferOceanCreatorFactory(PropertiesReader)
    OceanCreator createOceanCreator()
}
XmlWithFileChangeBufferOceanCreatorFactory -> PropertiesReader

interface OceanSimulationConfigurator{
    +OceanSimulation createOceanSimulation()
}

OceanSimulationConfigurator <|-- DefaultOceanSimulationConfigurator
class DefaultOceanSimulationConfigurator{
    -oceanCreatorFactory : OceanCreatorFactory
    +OceanSimulationConfigurator(OceanCreatorFactory)
    +OceanSimulation createOceanSimulation()
    -void createOceanRunner()
    -void createOceanRenderer()
    -void createOceanMetricPrinter()

}

DefaultOceanSimulationConfigurator --> OceanCreator


Main --> MainController
Main --> OceanCreatorFactory
DefaultMainController -> OceanSimulationConfigurator

interface MainController{
    void start()
}

MainController <|-- DefaultMainController
class DefaultMainController{
    -simulationConfigurator :OceanSimulationConfigurator
    +void start()
}

DefaultMainController --> OceanSimulation

interface PropertiesReader{
    +Map<String,String> readProperties()
}

PropertiesReader <|-- DefaultPropertiesReader

class DomOceanParametersReader{
    +OceanParameters read(InputStream inputStream)
    -DocumentBuilder createDocumentBuilder()
	-void startParse(Document document)
	-void parsePassiveFishParameters(Element passiveFishParameters)
	-void parseAggressiveFishParameters(Element aggressiveFishParameters)
	-void parseAggressiveFishCount(Element aggressiveFishCountElement)
	-void parsePassiveFishCount(Element passiveFishCountElement)
	-void parseOceanFlow(Element flowElement)
	-void parseOceanSize(Element oceanSizeElement)
	-void parseOceanType(Node oceanTypeNode)
	-FishParameters parseFishParameters(Element fishParametersElement)
	-Vector parseVector(Element vectorElement)
	-Integer parseIntegerAtTag(Element element, String tagName)
	-Integer parseInteger(Node integerNode)
	-Element getFirstElementByTagName(Element elementToSearch, String tagName)
}

class SaxOceanParametersReader{
	-OceanParameters oceanParameters;
    -Flow flow;
    -Vector sizeVector;
    -Vector directionVector;
    -OceanType oceanType;
    -FishParameters agrFishParams;
    -FishParameters pasFishParams;
    -String charactersIdentifier;
    -String coordsIdentifier;
    -String fishStrategyIdentifier;
    -StringBuffer oceanTypeBuffer;
    -StringBuffer sizeXBuffer;
    -StringBuffer sizeYBuffer;
    -StringBuffer directionXBuffer;
    -StringBuffer directionYBuffer;
    -StringBuffer strengthBuffer;
    -StringBuffer agrCountBuffer;
    -StringBuffer pasCountBuffer;
    -StringBuffer pasLifeTimeBuffer;
    -StringBuffer pasReproductionPeriodBuffer;
    -StringBuffer pasSmellSenseDistanceBuffer;
    -StringBuffer pasStarvationTimeBuffer;
    -StringBuffer agrLifeTimeBuffer;
    -StringBuffer agrReproductionPeriodBuffer;
    -StringBuffer agrSmellSenseDistanceBuffer;
    -StringBuffer agrStarvationTimeBuffer;
    +OceanParameters read(InputStream inputStream)
    +void startElement(String namespaceURI, String localName, String qualifiedName, Attributes attrs)
    +void characters(char[] ch, int start, int length)
	+void endElement(String nameURI, String localName, String qualifiedName)
}

class JaxbOceanParametersReader{
    +OceanParameters read(InputStream inputStream)
}

class DefaultOceanMetricPrinter{
    -metricEvaluators : List<MetricEvaluator>
    -metricWriter : OceanMetricWriter
}
DefaultOceanMetricPrinter --> MetricEvaluator
DefaultOceanMetricPrinter --> BlockingQueue
DefaultOceanMetricPrinter --> OceanMetricWriter

interface MetricEvaluator{
    Metric calculateMetric(OceanDto)
}

MetricEvaluator <|-- PassiveFishCountMetricEvaluator
MetricEvaluator <|-- AggressiveFishCountMetricEvaluator

interface OceanMetricWriter{
    +void write(List<Metric> metrics, OutputStream outputStream)
}

interface BlockingQueue{

}

OceanMetricWriter <|-- DomOceanMetricWriter
class DomOceanMetricWriter{
    +void write(List<Metric> metrics, OutputStream outputStream)
    -DOMSource makeDom(List<Metric> metrics)
    -Transformer createTransformer()
    -DocumentBuilder createDocumentBuilder()
    -Element createIntegerElementWithTextValue(Document document, String tagName, Integer value)
    -Element createMetricElement(Document document, Metric metric)
    -Element createMetricListElement(Document document, List<Element> metricElements)
}

OceanMetricWriter <|-- SaxOceanMetricWriter
class SaxOceanMetricWriter{
	-TransformerFactory factory;
    -SAXTransformerFactory saxTransFactory;
    -TransformerHandler transHandler;
    -List<Metric> metrics;
    +void write(List<Metric> metrics, OutputStream outputStream)
    -void writeRoot()
    -void writeMetrics()
}

OceanMetricWriter <|-- JaxbOceanMetricWriter
class JaxbOceanMetricWriter{
    +void write(List<Metric> metrics, OutputStream outputStream)
}
@enduml